CREATE SCHEMA IF NOT EXISTS SCHEMA1;

-- SCHEMA1.PARENT definição

-- Drop table

-- DROP TABLE SCHEMA1.PARENT;

CREATE TABLE IF NOT EXISTS SCHEMA1.PARENT (
	COMMON_ID_1 VARCHAR(255) NOT NULL,
	COMMON_ID_2 VARCHAR(255) NOT NULL,
	COMMON_ID_3 VARCHAR(255) NOT NULL,
	PARENT_COLUMN_1 VARCHAR(255),
	PARENT_COLUMN_2 VARCHAR(255),
	PARENT_UPDATE TIMESTAMP,
	CONSTRAINT PARENT_PK PRIMARY KEY (COMMON_ID_1,COMMON_ID_2,COMMON_ID_3)
);

-- SCHEMA1.CHILD definição

-- Drop table

-- DROP TABLE SCHEMA1.CHILD;

CREATE TABLE IF NOT EXISTS SCHEMA1.CHILD (
	COMMON_ID_1 VARCHAR(255) NOT NULL,
	COMMON_ID_2 VARCHAR(255) NOT NULL,
	COMMON_ID_3 VARCHAR(255) NOT NULL,
	CHILD_ID_4 INTEGER NOT NULL,
	CHILD_COLUMN_1 VARCHAR(255),
	CHILD_UPDATE TIMESTAMP,
	CONSTRAINT CHILD_PK PRIMARY KEY (COMMON_ID_1,COMMON_ID_2,COMMON_ID_3,CHILD_ID_4)
);

INSERT INTO SCHEMA1.PARENT
(COMMON_ID_1, COMMON_ID_2, COMMON_ID_3, PARENT_COLUMN_1, PARENT_COLUMN_2, PARENT_UPDATE)
VALUES('common-id-1', 'common-id-2', 'common-id-3', 'parent-field-1', 'parent-field-2', '2024-11-15 23:56:35.975');

INSERT INTO SCHEMA1.CHILD
(COMMON_ID_1, COMMON_ID_2, COMMON_ID_3, CHILD_ID_4, CHILD_COLUMN_1, CHILD_UPDATE)
VALUES('common-id-1', 'common-id-2', 'common-id-3', 0, 'child-0-field-1', '2024-11-15 23:56:35.975');



